### ISSUE TITLE
hammer search use too much memory

### ISSUE THREAD

**Issue by jianshu93** [zorino/kaamer#3]
Dear Maxime,

I notice that when I use kaammer -server with 64 threads for searching (refseq-bacteria database), the kaamer -search gradually takes more and more memory until the maximum of the machine (512G). I am wondering  how Mac memory I should assign to the searching process on a cluster to make sure that it is the most efficient and I do not waste any memory.

Thank you,

Jianshu

**Comment by zorino** [comment]
How do you proceed for your alignments, do launch several simultaneous search on large query datasets ?

**Comment by jianshu93** [comment]
no. I only lanch one search process. I have 10，000，000proteins for this search

Jianshu

________________________________

**Comment by zorino** [comment]
Ok try decreasing the number of threads to run the database.

**Comment by jianshu93** [comment]
Thanks it works now. It seems that downloading KEGG/biosys pathway and add it to the built database is very slow. How did you often do that? And I have to do it in an interactive way on clusters because I have to input yes in the terminal. Non-interactive way does not work, which is the most common case for a cluster when submitting jobs.  How about adding an option when downloading kaamer and says the user agree with the license of KEGG and BioSys? the server process can also be put into background after the database is opened successfully. It may be more convenient for clusters. What do you think?

Jianshu

**Comment by zorino** [comment]
The KEGG/biocyc download uses their respective API to query and fetch the information for each protein, so yes it will take a while.. you better not use a supercomputer for that kind of job.
