### ISSUE TITLE
ARM build nothing generated

### ISSUE THREAD

**Issue by jianshu93** [zorino/kaamer#5]
Hello Zerino,

I followed the install guide and run go install ./... in the directory in Go the newest version for MacOS M1, but I got nothing out. no info after running which kaamer

Any idea.

Thanks,

Jianshu

**Comment by zorino** [comment]
Do you have you gopath bin directory in your shell path ?

**Comment by jianshu93** [comment]
Thanks solved！Sorry I am new to Go but it is different：binaries are not copied to build directory.

thanks

Jianshu
